### ISSUE TITLE
Merge with openshift.ktz.cloud

### ISSUE THREAD

**Issue by ironicbadger** [openshifttips/web#28]
Would you be willing to merge with openshift.ktz.cloud?

I will handle the actual merging of content. I find this particularly hugo theme lacks a little in the usability department but you have a lot of great information that deserves a good search function!

**Comment by e-minguez** [comment]
> Would you be willing to merge with openshift.ktz.cloud?

Your website is definitely cool!
 
> I will handle the actual merging of content. I find this particularly hugo theme lacks a little in the usability department but you have a lot of great information that deserves a good search function!

Improving the site is in my to-do list, specifically the search function and the hugo theme.

What do you suggest in order to do the merge?

Thanks!!!

**Comment by IronicBadger** [comment]
I'll take all the content you have already and put it into the format we use? And then I could open a pull request against this repo and replace this one entirely if that's cool with you?

Then we can both own the repo but host the site using your awesome openshift.tips URL?

**Comment by e-minguez** [comment]
I would like to congratulate you for the compendium site, the tags, search engine, etc. is just awesome, I had something similar in mind when I started openshift.tips but I couldn't find anything similar so what I have now is the best one I found back in the day  I've seen you are using github actions and github pages with your custom domain, right?

I'm not by all means a web developer so I've just learned about this Gatsby thing... that's why I chose hugo, I just wanted to have something up & running quickly with github and Netlify (github pages didn't support custom domains with https back in the day), so I have a few questions:

- Is there a way to add an 'about' section? Just like https://openshift.tips/about/
- The theme switcher overlay doesn't allow you to select the upgrade nor vmware tags (just a nit)

Otherwise, I'm all in for the merge! I guess the process would be something like:

- Create a PR with the required modifications. This will modify the web building process to github actions and will require to switch to github pages.
- Disable netlify
- Profit!

I can give you write access to the repo once the merge is done, so we can both manage it!

Thanks!

**Comment by iranzo** [comment]
@IronicBadger what's the status for the PR that will cover this?

Thanks!
Pablo

**Comment by IronicBadger** [comment]
I've had little time lately but I will get to it.

**Comment by IronicBadger** [comment]
FYI - I'm about half way through. Hopefully will get a few hrs next week to finish up the migration of content. Then we should be in good shape to switch things over.
